apiVersion: v1
kind: Service
metadata:
  name: api-painter-frontend
spec:
  selector:
    app: api-painter-frontend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
